# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protofiles import service_pb2 as protofiles_dot_service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protofiles/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GatewayStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterBank = channel.unary_unary(
                '/p3.Gateway/RegisterBank',
                request_serializer=protofiles_dot_service__pb2.BankName.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Ack.FromString,
                _registered_method=True)
        self.ViewBalance = channel.unary_unary(
                '/p3.Gateway/ViewBalance',
                request_serializer=protofiles_dot_service__pb2.Token.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Balance.FromString,
                _registered_method=True)
        self.Login = channel.unary_unary(
                '/p3.Gateway/Login',
                request_serializer=protofiles_dot_service__pb2.Auth.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Token.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/p3.Gateway/Logout',
                request_serializer=protofiles_dot_service__pb2.Token.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Ack.FromString,
                _registered_method=True)
        self.TransferMoney = channel.unary_unary(
                '/p3.Gateway/TransferMoney',
                request_serializer=protofiles_dot_service__pb2.Transfer.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Ack.FromString,
                _registered_method=True)
        self.TransactionHistory = channel.unary_unary(
                '/p3.Gateway/TransactionHistory',
                request_serializer=protofiles_dot_service__pb2.Token.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.TransactionList.FromString,
                _registered_method=True)


class GatewayServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterBank(self, request, context):
        """For Bank 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Login(self, request, context):
        """For User
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransferMoney(self, request, context):
        """For Transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransactionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GatewayServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterBank': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterBank,
                    request_deserializer=protofiles_dot_service__pb2.BankName.FromString,
                    response_serializer=protofiles_dot_service__pb2.Ack.SerializeToString,
            ),
            'ViewBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewBalance,
                    request_deserializer=protofiles_dot_service__pb2.Token.FromString,
                    response_serializer=protofiles_dot_service__pb2.Balance.SerializeToString,
            ),
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=protofiles_dot_service__pb2.Auth.FromString,
                    response_serializer=protofiles_dot_service__pb2.Token.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=protofiles_dot_service__pb2.Token.FromString,
                    response_serializer=protofiles_dot_service__pb2.Ack.SerializeToString,
            ),
            'TransferMoney': grpc.unary_unary_rpc_method_handler(
                    servicer.TransferMoney,
                    request_deserializer=protofiles_dot_service__pb2.Transfer.FromString,
                    response_serializer=protofiles_dot_service__pb2.Ack.SerializeToString,
            ),
            'TransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.TransactionHistory,
                    request_deserializer=protofiles_dot_service__pb2.Token.FromString,
                    response_serializer=protofiles_dot_service__pb2.TransactionList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p3.Gateway', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('p3.Gateway', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gateway(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterBank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Gateway/RegisterBank',
            protofiles_dot_service__pb2.BankName.SerializeToString,
            protofiles_dot_service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Gateway/ViewBalance',
            protofiles_dot_service__pb2.Token.SerializeToString,
            protofiles_dot_service__pb2.Balance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Gateway/Login',
            protofiles_dot_service__pb2.Auth.SerializeToString,
            protofiles_dot_service__pb2.Token.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Gateway/Logout',
            protofiles_dot_service__pb2.Token.SerializeToString,
            protofiles_dot_service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransferMoney(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Gateway/TransferMoney',
            protofiles_dot_service__pb2.Transfer.SerializeToString,
            protofiles_dot_service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Gateway/TransactionHistory',
            protofiles_dot_service__pb2.Token.SerializeToString,
            protofiles_dot_service__pb2.TransactionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class BankStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Authenticate = channel.unary_unary(
                '/p3.Bank/Authenticate',
                request_serializer=protofiles_dot_service__pb2.Auth.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Ack.FromString,
                _registered_method=True)
        self.ViewBalance = channel.unary_unary(
                '/p3.Bank/ViewBalance',
                request_serializer=protofiles_dot_service__pb2.Auth.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Balance.FromString,
                _registered_method=True)
        self.PrepareCredit = channel.unary_unary(
                '/p3.Bank/PrepareCredit',
                request_serializer=protofiles_dot_service__pb2.CreditRequest.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Ack.FromString,
                _registered_method=True)
        self.PrepareDebit = channel.unary_unary(
                '/p3.Bank/PrepareDebit',
                request_serializer=protofiles_dot_service__pb2.DebitRequest.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Ack.FromString,
                _registered_method=True)
        self.CommitCredit = channel.unary_unary(
                '/p3.Bank/CommitCredit',
                request_serializer=protofiles_dot_service__pb2.CreditRequest.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Ack.FromString,
                _registered_method=True)
        self.CommitDebit = channel.unary_unary(
                '/p3.Bank/CommitDebit',
                request_serializer=protofiles_dot_service__pb2.DebitRequest.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Ack.FromString,
                _registered_method=True)
        self.AbortCredit = channel.unary_unary(
                '/p3.Bank/AbortCredit',
                request_serializer=protofiles_dot_service__pb2.CreditRequest.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Ack.FromString,
                _registered_method=True)
        self.AbortDebit = channel.unary_unary(
                '/p3.Bank/AbortDebit',
                request_serializer=protofiles_dot_service__pb2.DebitRequest.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.Ack.FromString,
                _registered_method=True)
        self.TransactionHistory = channel.unary_unary(
                '/p3.Bank/TransactionHistory',
                request_serializer=protofiles_dot_service__pb2.Auth.SerializeToString,
                response_deserializer=protofiles_dot_service__pb2.TransactionList.FromString,
                _registered_method=True)


class BankServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Authenticate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ViewBalance(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareCredit(self, request, context):
        """For Transaction
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareDebit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitCredit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommitDebit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortCredit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortDebit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TransactionHistory(self, request, context):
        """Get transaction history, now uses Auth
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Authenticate': grpc.unary_unary_rpc_method_handler(
                    servicer.Authenticate,
                    request_deserializer=protofiles_dot_service__pb2.Auth.FromString,
                    response_serializer=protofiles_dot_service__pb2.Ack.SerializeToString,
            ),
            'ViewBalance': grpc.unary_unary_rpc_method_handler(
                    servicer.ViewBalance,
                    request_deserializer=protofiles_dot_service__pb2.Auth.FromString,
                    response_serializer=protofiles_dot_service__pb2.Balance.SerializeToString,
            ),
            'PrepareCredit': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareCredit,
                    request_deserializer=protofiles_dot_service__pb2.CreditRequest.FromString,
                    response_serializer=protofiles_dot_service__pb2.Ack.SerializeToString,
            ),
            'PrepareDebit': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareDebit,
                    request_deserializer=protofiles_dot_service__pb2.DebitRequest.FromString,
                    response_serializer=protofiles_dot_service__pb2.Ack.SerializeToString,
            ),
            'CommitCredit': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitCredit,
                    request_deserializer=protofiles_dot_service__pb2.CreditRequest.FromString,
                    response_serializer=protofiles_dot_service__pb2.Ack.SerializeToString,
            ),
            'CommitDebit': grpc.unary_unary_rpc_method_handler(
                    servicer.CommitDebit,
                    request_deserializer=protofiles_dot_service__pb2.DebitRequest.FromString,
                    response_serializer=protofiles_dot_service__pb2.Ack.SerializeToString,
            ),
            'AbortCredit': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortCredit,
                    request_deserializer=protofiles_dot_service__pb2.CreditRequest.FromString,
                    response_serializer=protofiles_dot_service__pb2.Ack.SerializeToString,
            ),
            'AbortDebit': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortDebit,
                    request_deserializer=protofiles_dot_service__pb2.DebitRequest.FromString,
                    response_serializer=protofiles_dot_service__pb2.Ack.SerializeToString,
            ),
            'TransactionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.TransactionHistory,
                    request_deserializer=protofiles_dot_service__pb2.Auth.FromString,
                    response_serializer=protofiles_dot_service__pb2.TransactionList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'p3.Bank', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('p3.Bank', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Bank(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Authenticate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Bank/Authenticate',
            protofiles_dot_service__pb2.Auth.SerializeToString,
            protofiles_dot_service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ViewBalance(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Bank/ViewBalance',
            protofiles_dot_service__pb2.Auth.SerializeToString,
            protofiles_dot_service__pb2.Balance.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareCredit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Bank/PrepareCredit',
            protofiles_dot_service__pb2.CreditRequest.SerializeToString,
            protofiles_dot_service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareDebit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Bank/PrepareDebit',
            protofiles_dot_service__pb2.DebitRequest.SerializeToString,
            protofiles_dot_service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitCredit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Bank/CommitCredit',
            protofiles_dot_service__pb2.CreditRequest.SerializeToString,
            protofiles_dot_service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CommitDebit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Bank/CommitDebit',
            protofiles_dot_service__pb2.DebitRequest.SerializeToString,
            protofiles_dot_service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortCredit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Bank/AbortCredit',
            protofiles_dot_service__pb2.CreditRequest.SerializeToString,
            protofiles_dot_service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortDebit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Bank/AbortDebit',
            protofiles_dot_service__pb2.DebitRequest.SerializeToString,
            protofiles_dot_service__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TransactionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/p3.Bank/TransactionHistory',
            protofiles_dot_service__pb2.Auth.SerializeToString,
            protofiles_dot_service__pb2.TransactionList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
